/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AppLayout: typeof import('./components/Interface/AppLayout/AppLayout.vue')['default']
    AppLayoutToolbar: typeof import('./components/Interface/AppLayout/AppLayoutToolbar.vue')['default']
    DefaultLayout: typeof import('./components/Interface/Layouts/DefaultLayout/DefaultLayout.vue')['default']
    EmptyLayout: typeof import('./components/Interface/Layouts/EmptyLayout/EmptyLayout.vue')['default']
    HomeLayout: typeof import('./components/Interface/Layouts/EmptyLayout/HomeLayout.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TheHeader: typeof import('./components/Interface/TheHeader.vue')['default']
  }
}
