/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppLayout: typeof import('./components/Interface/AppLayout/AppLayout.vue')['default']
    AppLayoutToolbar: typeof import('./components/Interface/AppLayout/AppLayoutToolbar.vue')['default']
    AppToast: typeof import('./components/Interface/AppToast.vue')['default']
    DefaultLayout: typeof import('./components/Interface/Layouts/DefaultLayout/DefaultLayout.vue')['default']
    EmptyLayout: typeof import('./components/Interface/Layouts/EmptyLayout/EmptyLayout.vue')['default']
    ExampleDialog: typeof import('./components/Interface/ExampleDialog.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
